// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeFxnyhSyuMVShOOq-gKRi9baM7FLsd_w',
    appId: '1:919223369167:web:ef9dc7c02563c5531fa6ba',
    messagingSenderId: '919223369167',
    projectId: 'demooo-caac7',
    authDomain: 'demooo-caac7.firebaseapp.com',
    storageBucket: 'demooo-caac7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPhEdaaVkKQn4A6QZ3DwBsIbwEGJDpguc',
    appId: '1:919223369167:android:0176fc8e0c5f2daf1fa6ba',
    messagingSenderId: '919223369167',
    projectId: 'demooo-caac7',
    storageBucket: 'demooo-caac7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_ZV0vXBhPxPY6hRvDXaPVXO2ZLKbB5u8',
    appId: '1:919223369167:ios:ef25db4d8914a34c1fa6ba',
    messagingSenderId: '919223369167',
    projectId: 'demooo-caac7',
    storageBucket: 'demooo-caac7.appspot.com',
    iosBundleId: 'com.example.chatjptflutterProjecr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_ZV0vXBhPxPY6hRvDXaPVXO2ZLKbB5u8',
    appId: '1:919223369167:ios:ef25db4d8914a34c1fa6ba',
    messagingSenderId: '919223369167',
    projectId: 'demooo-caac7',
    storageBucket: 'demooo-caac7.appspot.com',
    iosBundleId: 'com.example.chatjptflutterProjecr',
  );
}
